"""Write safe, template-based Python packages under ``app/agents/generated/{slug}/``.

Runtime analysis still uses JSON specs on the run; these files are for humans, CI, and
reference. Code is fixed-template only — never executes LLM-produced Python as code.
"""

from __future__ import annotations

import re
from pathlib import Path

from app.schemas.custom_agent import BASE_DIMENSIONS, GeneratedCustomAgentSpec

_SLUG_RE = re.compile(r"^[a-z][a-z0-9_]{2,39}$")

# app/services/agent_module_export.py -> app/services -> app -> agents/generated
_GENERATED_ROOT = Path(__file__).resolve().parent.parent / "agents" / "generated"


def _validate_slug(slug: str) -> str:
    s = slug.strip()
    if not _SLUG_RE.match(s):
        raise ValueError(f"Invalid slug for export: {slug!r}")
    return s


def write_generated_agent_package(spec: GeneratedCustomAgentSpec) -> list[str]:
    """Create ``generated/{slug}/agent.py`` and ``system_prompt.txt``. Returns posix paths."""
    slug = _validate_slug(spec.slug)
    if spec.base_dimension not in BASE_DIMENSIONS:
        raise ValueError(f"Invalid base_dimension: {spec.base_dimension!r}")

    root = _GENERATED_ROOT / slug
    root.mkdir(parents=True, exist_ok=True)

    prompt_path = root / "system_prompt.txt"
    prompt_path.write_text(spec.system_prompt, encoding="utf-8")

    agent_py = root / "agent.py"
    agent_py.write_text(_render_agent_py(spec), encoding="utf-8")

    # Paths relative to backend package root (app/)
    rel = Path("app") / "agents" / "generated" / slug
    return [
        str(rel / "agent.py").replace("\\", "/"),
        str(rel / "system_prompt.txt").replace("\\", "/"),
    ]


def _render_agent_py(spec: GeneratedCustomAgentSpec) -> str:
    """Fixed template; dynamic strings use repr() for safe escaping."""
    slug = _validate_slug(spec.slug)
    return f'''\
# Generated by SafetyGuard — safe template (not LLM-written code).
# Runtime analysis uses the JSON spec on the run; this module mirrors it for repo/CI.
# slug={slug!r}

from __future__ import annotations

from pathlib import Path
from typing import Any

_SLUG = {slug!r}
_DISPLAY_NAME = {spec.display_name!r}
_BASE_DIMENSION = {spec.base_dimension!r}

_DIR = Path(__file__).resolve().parent
SYSTEM_PROMPT = (_DIR / "system_prompt.txt").read_text(encoding="utf-8")


async def run(state: dict[str, Any]) -> dict[str, Any]:
    """Entry point compatible with ``run_custom_dimension_agent``."""
    from app.agents._agent_base import run_custom_dimension_agent

    return await run_custom_dimension_agent(
        slug=_SLUG,
        display_name=_DISPLAY_NAME,
        base_dimension=_BASE_DIMENSION,
        system_prompt=SYSTEM_PROMPT,
        state=state,
        progress=55,
    )
'''
